apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:

#capacity and storage is dummy just for api defnition
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "" # for static provisoning sc class is empty
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: efs:fs-0c785690468420714)