apiVersion: v1
kind: pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: #softlimit
        cpu: "100m" #1000m is 1 cpu
        memory: "128Mi"
      limites: # hard limit
        cpu: "150m"
        memory: "256Mi"