apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    project: roboshop
    environment: dev
spec:
  # service uses the below labels to select pods
  type: NodePort
  selector:
    project: roboshop
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port