apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        roject: roboshop
        tier: frontend
        component: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
